# Generated by Django 4.2.24 on 2025-09-22 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0002_alter_dailyrecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer", name="name", field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="customer", unique_together={("user", "name")},
        ),
    ]
