# Generated by Django 4.2.24 on 2025-09-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_customer_user_alter_dailyrecord_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="dailyrecord", unique_together=set(),),
        migrations.AddConstraint(
            model_name="dailyrecord",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_user_date"
            ),
        ),
    ]
