# Generated by Django 4.2.24 on 2025-09-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_dailyrecord_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="dailyrecord", name="customer_debts",),
        migrations.RemoveField(model_name="dailyrecord", name="debts_paid",),
        migrations.RemoveField(model_name="dailyrecord", name="expenses",),
        migrations.RemoveField(model_name="dailyrecord", name="purchases",),
        migrations.RemoveField(model_name="dailyrecord", name="workers_wages",),
    ]
